# Generated by Django 4.1.13 on 2024-07-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_product_photo_alter_invoice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='min_bottles',
            field=models.IntegerField(default=0),
        ),
    ]
