# Generated by Django 4.1.13 on 2024-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bottle_min_bottles'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bottle_images/'),
        ),
    ]
