# Generated by Django 4.1.13 on 2024-08-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_email_alter_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bottle')),
            ],
        ),
        migrations.AlterField(
            model_name='clientorders',
            name='is_confirmed',
            field=models.CharField(choices=[('pending_confirm', 'Pending Confirmation'), ('confirmed', 'Confirmed')], default='pending_confirm', max_length=20),
        ),
        migrations.CreateModel(
            name='PackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bottles', models.ManyToManyField(through='core.BottleQuantity', to='core.bottle')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bottlequantity',
            name='pack_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.packrule'),
        ),
    ]
