# Generated by Django 4.1.13 on 2024-08-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bottlequantity_alter_clientorders_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packrule',
            name='general_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='packrule',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
