# Generated by Django 4.1.13 on 2024-08-10 21:50

import core.utils.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_packrule_general_quantity_packrule_is_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, storage=core.utils.storage_backend.PublicUploadStorage(), upload_to='bottle_images/'),
        ),
    ]
