# Generated by Django 4.1.13 on 2024-08-10 22:34

import core.utils.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bottle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='product_photo',
            field=models.ImageField(blank=True, default='', null=True, storage=core.utils.storage_backend.PublicUploadStorage(), upload_to='invoice_photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, storage=core.utils.storage_backend.PublicUploadStorage(), upload_to='product_images/'),
        ),
    ]
