# Generated by Django 4.1.13 on 2024-08-11 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_invoice_picker_ci_remove_invoice_picker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
