# Generated by Django 4.1.13 on 2024-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
