# Generated by Django 4.1.13 on 2024-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_client_phone_number_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='bottle_range',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='min_bottles',
            field=models.IntegerField(default=3),
        ),
    ]
