# Generated by Django 4.1.13 on 2024-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clientorders_client_email_invoice_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
