from .dashboardViews import *
from .userViews import *
from .productViews import *
from .stockViews import *
from .roleViews import *
from .invoiceViews import *
from .pointsViews import *
from .storeViews import *
from .cityViews import *
from .bottleViews import *